cal_data = {
  2020: {
    10: {
      7: ["Piloto Virtual del Módulo 1 de Capacitación para RC. Primera Parte.  17:00 hrs."],
      8: ["Piloto Virtual del Módulo 1 de Capacitación para RC. Segunda Parte. 17:00 hrs."],
      14: ["Talleres Virtuales para Instructores de Capacitación para RC y RG en cada Distrito Electoral Federal. Módulo 1. Primera Parte. 9:00 a 20:00 hrs."],
      15: ["Talleres Virtuales para Instructores de Capacitación para RC y RG en cada Distrito Electoral Federal. Módulo 1. Segunda Parte. 9:00 a 20:00 hrs."],
      22: ["Encuentro de Capacitación Electoral con Coordinadores de Representantes Generales (CRG). 15:00 hrs."],
      25: ["Taller Virtual para Instructores de Capacitación para RC y RG de  todos los Distritos Electorales Federales. Módulo 1. Primera Parte. 18:00 a 20:00 hrs."],
      26: ["Taller Virtual para Instructores de Capacitación para RC y RG de  todos los Distritos Electorales Federales. Módulo 1. Segunda Parte. 18:00 a 20:00 hrs."],
      28: ["Reunión Virtual con Instructores de RC y RG sobre Aspectos Organizativos de la Capacitación. Todos los Distritos Electorales Federales. 16:00 hrs."],
      29: ["Reuniones-Taller Virtual con Instructores de cada Distrito Electoral Federal sobre uso básico de la plataforma zoom. 9:00 a 16:00 hrs."]
    },
    11: {
      5: ["Capacitación de Representantes Generales del Distrito 3. 16:00 hrs."],
      10: ["Capacitación para RC del Distrito 3. 18:00 hrs."],
      12: ["Capacitación de RG del Distrito 5. 15:00 hrs.",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 1. 16:00 hrs.",
           "Capacitación de RG del Distrito 3 (parte 2). 17:00 hrs.",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 2. 18:00 hrs."],
      13: ["Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 4. 16:00 hrs.",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 7. 18:00 hrs."],
      16: ["Capacitación de RC del Distrito 5. 16:00 hrs."],
      17: ["Capacitación de RC del Distrito 3 (parte 2). 18:00 hrs.",
           "Capacitación de RG del Distrito 4. 17:00 hrs."],
      18: ["Capacitación de Instructores de todos los distritos. 17:00 hrs.",
           "Capacitación de RC del Distrito 5. 19:00 hrs."],
      20: ["Capacitación de RC del Distrito 5. 9:00 hrs. (cancelada)"],
      21: ["Capacitación de Instructores de todos los Distritos (parte 2). 17:00 hrs.",
           "Capacitación de RG del Distrito 2. 18:00 hrs."],
      22: ["Capacitación de RG del Distrito 1. 17:00 hrs.",
           "Capacitación de RC del Distrito 3. 17:00 hrs."],
      23: ["Capacitación de RG del Distrito 6. 17:00 hrs."]
    }
  },
  2021: {
    0: {
      7: ["Capacitación de RG del Distrito 2. 18:00 hrs."],
      8: ["Capacitación de RG del Distrito 2. 18:00 hrs."],
      9: ["Capacitación de RG del Distrito 2. 10:00 hrs."],
      11: ["Capacitación de Instructores de todos los Distritos. 17:00 hrs."],
      12: ["Capacitación de RC del Distrito 5. 19:00 hrs."],
      13: ["Capacitación de RG del Distrito 6. 17:00 hrs."],
      14: ["Capacitación de RG del Distrito 1. 18:00 hrs.",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 2. 17:00 hrs. (cancelada)",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 6. 18:00 hrs. (cancelada)",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 7. 19:00 hrs."],
      15: ["Capacitación de Instructores de todos los Distritos (parte 2). 17:00 hrs.",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 6. 18:00 hrs.",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 2. 19:00 hrs."],
      16: ["Capacitación de RC del Distrito 5. 16:00 hrs.",
           "Capacitación de RC del Distrito 2. 16:00 hrs."],
      17: ["Capacitación de RG del Distrito 2. 12:00 hrs.",
           "Capacitación de RG del Distrito 7. 12:00 hrs."],
      19: ["Capacitación de RG del Distrito 5. 19:00 hrs."],
      20: ["Capacitación de RG del Distrito 6. 17:00 hrs. (cancelada)"],
      21: ["Capacitación Municipal de RG. 16:00 hrs.",
           "Capacitación de RC del Distrito 2. 18:00 hrs."],
      22: ["Capacitación de RC del Distrito 1. 18:00 hrs.",
           "Capacitación de RC del Distrito 2. 18:00 hrs. (cancelada)",
           "Capacitación de RC del Distrito 5. 19:00 hrs. (cancelada)"],
      23: ["Capacitación de RG del Distrito 2. 16:00 hrs.",
           "Capacitación de RC del Distrito 5. 19:00 hrs. (cancelada)"],
      24: ["Capacitación de RC del Distrito 1 presencial en oficinas Morena de Caborca. 10:00 hrs.",
           "Capacitación de RC del Distrito 2. 16:00 hrs.",
           "Capacitación de RG del Distrito 4. 16:00 hrs.",
           "Capacitación Municipal de RG. 19:00 hrs."],
      27: ["Capacitación de RC del Distrito 1 presencial en Puerto Peñasco. 17:00 hrs. (cancelada)",
           "Capacitación de RG del Distrito 6. 17:00 hrs.",
           "Capacitación Municipal de RG. 18:00 hrs."],
      28: ["Capacitación de RC del Distrito 3. 18:00 hrs.",
           "Capacitación de RC del Distrito 5. 19:00 hrs."],
      30: ["Capacitación de RC del Distrito 3. 11:00 hrs."],
      31: ["Capacitación de RC del Distrito 1 presencial en oficinas Morena de Caborca. 10:00 hrs."]
    },
    1: {
      1: ["Capacitación de RC del Distrito 3. 15:00 hrs."],
      3: ["Capacitación de RC del Distrito 1 presencial en Local de Morena de Caborca. 15:00 hrs."],
      4: ["Capacitación de RC del Distrito 1 presencial en Puerto Peñasco. 18:00 hrs.",
          "Capacitación de RC del Distrito 3. 19:00 hrs.",
          "Capacitación de RG del Distrito 1. 19:30 hrs."],
      5: ["Capacitación de RC del Distrito 3 presencial en Colonia Cuatro Olivos de Hermosillo. 18:00 hrs.",
          "Capacitación de RC del Distrito 1. 18:00 hrs."],
      6: ["Capacitación de RG del Distrito 3. 16:00 hrs.",
          "Capacitación Municipal de RG. 18:00 hrs."],
      7: ["Capacitación de RC del Distrito 1 presencial en oficinas Morena de Caborca. 9:00 hrs.",
          "Capacitación de RC del Distrito 1 presencial en Colonia Topahue en SLRC. 16:00 hrs."],
      8: ["Capacitación de RC del Distrito 5. 19:00 hrs.",
          "Capacitación de RC del Distrito 1 presencial en oficinas de Morena de Sonoyta. 20:00 hrs."],
      9: ["Taller virtual para instructores de Capacitación de RC. 19:00 hrs."],
      10: ["Capacitación Municipal de RC. 18:00 hrs."],
      11: ["Capacitación de RC del Distrito 2. 16:00 hrs.",
           "Capacitación de RC del Distrito 3. 18:00 hrs.",
           "Capacitación Municipal de RC. 18:00 hrs.",
           "Capacitación de RC del Distrito 1 presencial en Puerto Peñasco. 18:00 hrs.",
           "Capacitación de RC del Distrito 2. 19:00 hrs."],
      12: ["Capacitación de RC del Distrito 2. 16:00 hrs. (cancelada)",
           "Capacitación Municipal de RC. 18:00 hrs.",
           "Capacitación de RC del Distrito 2. 19:00 hrs.",
           "Capacitación de RC del Distrito 1. 19:30 hrs."],
      13: ["Capacitación de RC del Distrito 2. 12:00 hrs. (cancelada)",
           "Capacitación de RC del Distrito 5. 16:00 hrs.",
           "Capacitación de RC del Distrito 1 presencial en Oficina de Morena en SLRC. 16:00 hrs.",
           "Capacitación de RC del Distrito 2. 16:00 hrs.",
           "Capacitación de RC del Distrito 2. 19:00 hrs."],
      14: ["Capacitación de RG del Distrito 7 presencial en Comité de Morena de Navojoa. 9:00 hrs.",
           "Capacitación de RC del Distrito 1 presencial en oficinas Morena de Caborca. 10:00 hrs.",
           "Capacitación de RC del Distrito 2. 12:00 hrs. (cancelada)",
           "Capacitación Municipal de RC. 14:00 hrs. (cancelada)",
           "Capacitación de RG del Distrito 7 presencial en Huatabampo. 15:00 hrs.",
           "Capacitación de RC del Distrito 3 presencial en Poblado Miguel Alemán. 16:00 hrs.",
           "Capacitación de RC del Distrito 2. 16:00 hrs. (cancelada)",
           "Capacitación de RC del Distrito 3. 17:00 hrs.",
           "Capacitación de RC del Distrito 2. 19:00 hrs."],
      15: ["Capacitación de RC del Distrito 5. 19:00 hrs."],
      17: ["Capacitación de RC del Distrito 1 presencial en Oficina de Morena en Puerto Peñasco. 17:00 hrs.",
	   "Capacitación de RG del Distrito 5. 18:00 hrs.",
	   "Capacitación de RC del Distrito 4. 18:00 hrs.",
	   "Capacitación de RG del Distrito 1. 19:30 hrs."],
      18: ["Capacitación de RC del Distrito 5. 9:00 hrs.",
	   "Capacitación de RC del Distrito 4 presencial en Empalme. 17:00 hrs.",
	   "Capacitación de RG del Distrito 3. 18:00 hrs.",
	   "Capacitación de RC del Distrito 1 presencial en Oficina de Morena en Puerto Peñasco. 18:00 hrs.",
	   "Capacitación de RC del Distrito 2. 19:00 hrs."],
      19: ["Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Navojoa. 17:00 hrs.",
	   "Capacitación de RC del Distrito 1. 19:30 hrs. (suspendida)"],
      20: ["Capacitación de RC del Distrito 4 presencial en Villa Hidalgo. 9:00 hrs.",
	   "Capacitación de RC del Distrito 2 presencial en Local de Morena en Cananea. 10:00 hrs.",
	   "Capacitación de RC del Distrito 3. 10:00 hrs.",
	   "Capacitación Municipal de RG. 11:00 hrs.",
	   "Capacitación de RC del Distrito 4 presencial en Granados o Huásabas. 13:00 hrs.",
	   "Capacitación de RC del Distrito 2 presencial en Local de Morena en Cananea. 16:00 hrs.",
	   "Capacitación Municipal de RC. 16:00 hrs.",
	   "Capacitación de RC del Distrito 1 presencial en Av. España 10 y 11 en SLRC. 16:30 hrs.",
	   "Capacitación de RC del Distrito 3. 17:00 hrs.",
	   "Capacitación de RC del Distrito 4 presencial en Bacadehuachi. 17:30 hrs."],
      21: ["Capacitación de RC del Distrito 5 presencial en Col. Country Club en Hermosillo. 10:00 hrs.",
	   "Capacitación de RC del Distrito 7 presencial en domicilio particular en Navojoa. 11:00 hrs.",
	   "Capacitación de RC del Distrito 4 presencial en Bavispe. 12:00 hrs.",
	   "Capacitación de RC del Distrito 1 presencial en Oficina de Morena en SLRC. 16:00 hrs.",
	   "Capacitación de RC del Distrito 2. 16:00 hrs.",
	   "Capacitación de RC del Distrito 7 presencial en domicilio particular en Navojoa. 17:00 hrs.",
	   "Capacitación de RC del Distrito 2. 19:00 hrs."],
      22: ["Capacitación de RC del Distrito 7 presencial en Comité Morena en Álamos. 15:00 hrs.",
	   "Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Navojoa. 16:00 hrs.",
	   "Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Etchojoa. 17:00 hrs."],
      23: ["Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Etchojoa. 16:00 hrs.",
	   "Capacitación de RC/RG del Distrito 6 presencial en Col. Casa Blanca en Cd. Obregón. 16:00 hrs."],
      24: ["Capacitación de RC/RG del Distrito 6 presencial en Calle Juárez en Esperanza. 17:00 hrs."],
      25: ["Capacitación de RG del Distrito 2 presencial en Nogales. 11:00 hrs.",
	   "Capacitación de RG del Distrito 2. 16:00 hrs.",
	   "Capacitación de RC del Distrito 5. 19:00 hrs."],
      26: ["Capacitación de RG del Distrito 2 presencial en Nogales. 11:00 hrs.",
	   "Capacitación de RC del Distrito 3. 17:00 hrs."],
      28: ["Capacitación de RC del Distrito 3 presencial en Poblado Miguel Alemán. 17:00 hrs."]
    }
  }
};
