cal_data = {
  2020: {
    10: {
      7: ["Piloto Virtual del Módulo 1 de Capacitación para RC. Primera Parte.  17:00 hrs."],
      8: ["Piloto Virtual del Módulo 1 de Capacitación para RC. Segunda Parte. 17:00 hrs."],
      14: ["Talleres Virtuales para Instructores de Capacitación para RC y RG en cada Distrito Electoral Federal. Módulo 1. Primera Parte. 9:00 a 20:00 hrs."],
      15: ["Talleres Virtuales para Instructores de Capacitación para RC y RG en cada Distrito Electoral Federal. Módulo 1. Segunda Parte. 9:00 a 20:00 hrs."],
      22: ["Encuentro de Capacitación Electoral con Coordinadores de Representantes Generales (CRG). 15:00 hrs."],
      25: ["Taller Virtual para Instructores de Capacitación para RC y RG de  todos los Distritos Electorales Federales. Módulo 1. Primera Parte. 18:00 a 20:00 hrs."],
      26: ["Taller Virtual para Instructores de Capacitación para RC y RG de  todos los Distritos Electorales Federales. Módulo 1. Segunda Parte. 18:00 a 20:00 hrs."],
      28: ["Reunión Virtual con Instructores de RC y RG sobre Aspectos Organizativos de la Capacitación. Todos los Distritos Electorales Federales. 16:00 hrs."],
      29: ["Reuniones-Taller Virtual con Instructores de cada Distrito Electoral Federal sobre uso básico de la plataforma zoom. 9:00 a 16:00 hrs."]
    },
    11: {
      5: ["Capacitación de Representantes Generales del Distrito 3. 16:00 hrs."],
      10: ["Capacitación para RC del Distrito 3. 18:00 hrs."],
      12: ["Capacitación de RG del Distrito 5. 15:00 hrs.",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 1. 16:00 hrs.",
           "Capacitación de RG del Distrito 3 (parte 2). 17:00 hrs.",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 2. 18:00 hrs."],
      13: ["Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 4. 16:00 hrs.",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 7. 18:00 hrs."],
      16: ["Capacitación de RC del Distrito 5. 16:00 hrs."],
      17: ["Capacitación de RC del Distrito 3 (parte 2). 18:00 hrs.",
           "Capacitación de RG del Distrito 4. 17:00 hrs."],
      18: ["Capacitación de Instructores de todos los distritos. 17:00 hrs.",
           "Capacitación de RC del Distrito 5. 19:00 hrs."],
      20: ["Capacitación de RC del Distrito 5. 9:00 hrs. (cancelada)"],
      21: ["Capacitación de Instructores de todos los Distritos (parte 2). 17:00 hrs.",
           "Capacitación de RG del Distrito 2. 18:00 hrs."],
      22: ["Capacitación de RG del Distrito 1. 17:00 hrs.",
           "Capacitación de RC del Distrito 3. 17:00 hrs."],
      23: ["Capacitación de RG del Distrito 6. 17:00 hrs."]
    }
  },
  2021: {
    0: {
      7: ["Capacitación de RG del Distrito 2. 18:00 hrs."],
      8: ["Capacitación de RG del Distrito 2. 18:00 hrs."],
      9: ["Capacitación de RG del Distrito 2. 10:00 hrs."],
      11: ["Capacitación de Instructores de todos los Distritos. 17:00 hrs."],
      12: ["Capacitación de RC del Distrito 5. 19:00 hrs."],
      13: ["Capacitación de RG del Distrito 6. 17:00 hrs."],
      14: ["Capacitación de RG del Distrito 1. 18:00 hrs.",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 2. 17:00 hrs. (cancelada)",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 6. 18:00 hrs. (cancelada)",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 7. 19:00 hrs."],
      15: ["Capacitación de Instructores de todos los Distritos (parte 2). 17:00 hrs.",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 6. 18:00 hrs.",
           "Reunión de avance de tareas de organización de la capacitación del Distrito Electoral Federal 2. 19:00 hrs."],
      16: ["Capacitación de RC del Distrito 5. 16:00 hrs.",
           "Capacitación de RC del Distrito 2. 16:00 hrs."],
      17: ["Capacitación de RG del Distrito 2. 12:00 hrs.",
           "Capacitación de RG del Distrito 7. 12:00 hrs."],
      19: ["Capacitación de RG del Distrito 5. 19:00 hrs."],
      20: ["Capacitación de RG del Distrito 6. 17:00 hrs. (cancelada)"],
      21: ["Capacitación Municipal de RG. 16:00 hrs.",
           "Capacitación de RC del Distrito 2. 18:00 hrs."],
      22: ["Capacitación de RC del Distrito 1. 18:00 hrs.",
           "Capacitación de RC del Distrito 2. 18:00 hrs. (cancelada)",
           "Capacitación de RC del Distrito 5. 19:00 hrs. (cancelada)"],
      23: ["Capacitación de RG del Distrito 2. 16:00 hrs.",
           "Capacitación de RC del Distrito 5. 19:00 hrs. (cancelada)"],
      24: ["Capacitación de RC del Distrito 1 presencial en oficinas Morena de Caborca. 10:00 hrs.",
           "Capacitación de RC del Distrito 2. 16:00 hrs.",
           "Capacitación de RG del Distrito 4. 16:00 hrs.",
           "Capacitación Municipal de RG. 19:00 hrs."],
      27: ["Capacitación de RC del Distrito 1 presencial en Puerto Peñasco. 17:00 hrs. (cancelada)",
           "Capacitación de RG del Distrito 6. 17:00 hrs.",
           "Capacitación Municipal de RG. 18:00 hrs."],
      28: ["Capacitación de RC del Distrito 3. 18:00 hrs.",
           "Capacitación de RC del Distrito 5. 19:00 hrs."],
      30: ["Capacitación de RC del Distrito 3. 11:00 hrs."],
      31: ["Capacitación de RC del Distrito 1 presencial en oficinas Morena de Caborca. 10:00 hrs."]
    },
    1: {
      1: ["Capacitación de RC del Distrito 3. 15:00 hrs."],
      3: ["Capacitación de RC del Distrito 1 presencial en Local de Morena de Caborca. 15:00 hrs."],
      4: ["Capacitación de RC del Distrito 1 presencial en Puerto Peñasco. 18:00 hrs.",
          "Capacitación de RC del Distrito 3. 19:00 hrs.",
          "Capacitación de RG del Distrito 1. 19:30 hrs."],
      5: ["Capacitación de RC del Distrito 3 presencial en Colonia Cuatro Olivos de Hermosillo. 18:00 hrs.",
          "Capacitación de RC del Distrito 1. 18:00 hrs."],
      6: ["Capacitación de RG del Distrito 3. 16:00 hrs.",
          "Capacitación Municipal de RG. 18:00 hrs."],
      7: ["Capacitación de RC del Distrito 1 presencial en oficinas Morena de Caborca. 9:00 hrs.",
          "Capacitación de RC del Distrito 1 presencial en Colonia Topahue en SLRC. 16:00 hrs."],
      8: ["Capacitación de RC del Distrito 5. 19:00 hrs.",
          "Capacitación de RC del Distrito 1 presencial en oficinas de Morena de Sonoyta. 20:00 hrs."],
      9: ["Taller virtual para instructores de Capacitación de RC. 19:00 hrs."],
      10: ["Capacitación Municipal de RC. 18:00 hrs."],
      11: ["Capacitación de RC del Distrito 2. 16:00 hrs.",
           "Capacitación de RC del Distrito 3. 18:00 hrs.",
           "Capacitación Municipal de RC. 18:00 hrs.",
           "Capacitación de RC del Distrito 1 presencial en Puerto Peñasco. 18:00 hrs.",
           "Capacitación de RC del Distrito 2. 19:00 hrs."],
      12: ["Capacitación de RC del Distrito 2. 16:00 hrs. (cancelada)",
           "Capacitación Municipal de RC. 18:00 hrs.",
           "Capacitación de RC del Distrito 2. 19:00 hrs.",
           "Capacitación de RC del Distrito 1. 19:30 hrs."],
      13: ["Capacitación de RC del Distrito 2. 12:00 hrs. (cancelada)",
           "Capacitación de RC del Distrito 5. 16:00 hrs.",
           "Capacitación de RC del Distrito 1 presencial en Oficina de Morena en SLRC. 16:00 hrs.",
           "Capacitación de RC del Distrito 2. 16:00 hrs.",
           "Capacitación de RC del Distrito 2. 19:00 hrs."],
      14: ["Capacitación de RG del Distrito 7 presencial en Comité de Morena de Navojoa. 9:00 hrs.",
           "Capacitación de RC del Distrito 1 presencial en oficinas Morena de Caborca. 10:00 hrs.",
           "Capacitación de RC del Distrito 2. 12:00 hrs. (cancelada)",
           "Capacitación Municipal de RC. 14:00 hrs. (cancelada)",
           "Capacitación de RG del Distrito 7 presencial en Huatabampo. 15:00 hrs.",
           "Capacitación de RC del Distrito 3 presencial en Poblado Miguel Alemán. 16:00 hrs.",
           "Capacitación de RC del Distrito 2. 16:00 hrs. (cancelada)",
           "Capacitación de RC del Distrito 3. 17:00 hrs.",
           "Capacitación de RC del Distrito 2. 19:00 hrs."],
      15: ["Capacitación de RC del Distrito 5. 19:00 hrs."],
      17: ["Capacitación de RC del Distrito 1 presencial en Oficina de Morena en Puerto Peñasco. 17:00 hrs.",
	   "Capacitación de RG del Distrito 5. 18:00 hrs.",
	   "Capacitación de RC del Distrito 4. 18:00 hrs.",
	   "Capacitación de RG del Distrito 1. 19:30 hrs."],
      18: ["Capacitación de RC del Distrito 5. 9:00 hrs.",
	   "Capacitación de RC del Distrito 4 presencial en Empalme. 17:00 hrs.",
	   "Capacitación de RG del Distrito 3. 18:00 hrs.",
	   "Capacitación de RC del Distrito 1 presencial en Oficina de Morena en Puerto Peñasco. 18:00 hrs.",
	   "Capacitación de RC del Distrito 2. 19:00 hrs."],
      19: ["Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Navojoa. 17:00 hrs.",
	   "Capacitación de RC del Distrito 1. 19:30 hrs. (suspendida)"],
      20: ["Capacitación de RC del Distrito 4 presencial en Villa Hidalgo. 9:00 hrs.",
	   "Capacitación de RC del Distrito 2 presencial en Local de Morena en Cananea. 10:00 hrs.",
	   "Capacitación de RC del Distrito 3. 10:00 hrs.",
	   "Capacitación Municipal de RG. 11:00 hrs.",
	   "Capacitación de RC del Distrito 4 presencial en Granados o Huásabas. 13:00 hrs.",
	   "Capacitación de RC del Distrito 2 presencial en Local de Morena en Cananea. 16:00 hrs.",
	   "Capacitación Municipal de RC. 16:00 hrs.",
	   "Capacitación de RC del Distrito 1 presencial en Av. España 10 y 11 en SLRC. 16:30 hrs.",
	   "Capacitación de RC del Distrito 3. 17:00 hrs.",
	   "Capacitación de RC del Distrito 4 presencial en Bacadehuachi. 17:30 hrs."],
      21: ["Capacitación de RC del Distrito 5 presencial en Col. Country Club en Hermosillo. 10:00 hrs.",
	   "Capacitación de RC del Distrito 7 presencial en domicilio particular en Navojoa. 11:00 hrs.",
	   "Capacitación de RC del Distrito 4 presencial en Bavispe. 12:00 hrs.",
	   "Capacitación de RC del Distrito 1 presencial en Oficina de Morena en SLRC. 16:00 hrs.",
	   "Capacitación de RC del Distrito 2. 16:00 hrs.",
	   "Capacitación de RC del Distrito 7 presencial en domicilio particular en Navojoa. 17:00 hrs.",
	   "Capacitación de RC del Distrito 2. 19:00 hrs."],
      22: ["Capacitación de RC del Distrito 7 presencial en Comité Morena en Álamos. 15:00 hrs.",
	   "Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Navojoa. 16:00 hrs.",
	   "Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Etchojoa. 17:00 hrs."],
      23: ["Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Etchojoa. 16:00 hrs.",
	   "Capacitación de RC/RG del Distrito 6 presencial en Col. Casa Blanca en Cd. Obregón. 16:00 hrs."],
      25: ["Capacitación de RG del Distrito 2 presencial en Nogales. 11:00 hrs.",
	   "Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Etchojoa. 17:00 hrs.",
	   "Capacitación de RC del Distrito 7 presencial en domicilio particular en Navojoa. 18:00 hrs.",
	   "Capacitación de RC del Distrito 3 presencial en Blvd. Luis Encinas en Hermosillo. 18:30 hrs.",
	   "Capacitación de RC del Distrito 5. 19:00 hrs."],
      26: ["Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Navojoa. 10:00 hrs.",
	   "Capacitación de RG del Distrito 2 presencial en Nogales. 11:00 hrs.",
	   "Capacitación de RC del Distrito 3. 17:00 hrs.",
	   "Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Etchojoa. 17:00 hrs.",
	   "Capacitación de RC del Distrito 6. 18:00 hrs.",
	   "Capacitación de RC del Distrito 1. 19:30 hrs."],
      27: ["Capacitación de RC del Distrito 1 presencial en Oficina de Morena en SLRC. 16:00 hrs.",
	   "Capacitación de RC del Distrito 6. 16:00 hrs.",
	   "Capacitación de RC del Distrito 7 presencial en Comunidad Mabejaqui en Etchojoa. 17:00 hrs.",
	   "Capacitación de RG del Distrito 6. 18:00 hrs."],
      28: ["Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Etchojoa. 9:00 hrs.",
	   "Capacitación de RC del Distrito 1 presencial en Oficina de Morena en Caborca. 10:00 hrs.",
	   "Capacitación de RC del Distrito 7 presencial en domicilio particular en Benito Juárez. 11:00 hrs.",
	   "Capacitación de RC del Distrito 1 presencial en domicilio particular Av Nuevo Leon en SLRC. 16:00 hrs.",
	   "Capacitación de RC del Distrito 6 presencial en Campo 30 en Cajeme. 16:30 hrs.",
	   "Capacitación de RC del Distrito 3 presencial en Poblado Miguel Alemán. 17:00 hrs."]
    },
    2: {
      1: ["Capacitación de RC del Distrito 7 presencial en Chucarit Etchojoa. 18:00 hrs.",
	  "Capacitación de RC del Distrito 1 presencial en Oficinas de Morena en Puerto Peñasco. 18:00 hrs."],
      2: ["Capacitación de RG del Distrito 1 presencial en Oficinas de Morena en Sonoyta. 14:00 hrs.",
	  "Capacitación de RC del Distrito 1 presencial en Oficinas de Morena en Sonoyta. 15:00 hrs.",
	  "Capacitación de RC del Distrito 6 presencial en Ciudad Obregón. 16:00 hrs.",
	  "Capacitación de RC del Distrito 1 presencial en Oficinas de Morena en Puerto Peñasco. 18:00 hrs."],
      3: ["Capacitación de RC del Distrito 7 presencial en domicilio particular en Bacobampo. 16:00 hrs.",
	  "Capacitación de RC del Distrito 1 presencial en Oficinas de Morena en Sonoyta. 17:00 hrs.",
	  "Taller virtual para instructores de Capacitación de RC. 17:00 hrs.",
	  "Capacitación de RC del Distrito 1 presencial en Oficinas de Morena en Puerto Peñasco. 19:00 hrs."],
      4: ["Capacitación de RC del Distrito 7 presencial en domicilio particular en Navojoa. 17:00 hrs.",
	  "Capacitación de RC del Distrito 1 presencial en Oficinas de Morena en Puerto Peñasco. 18:00 hrs.",
	  "Capacitación de RC del Distrito 5. 19:00 hrs."],
      5: ["Capacitación de RC del Distrito 2. 10:00 hrs.",
          "Capacitación de RC del Distrito 2 presencial en Oficinas de Morena en Agua Prieta. 16:00 hrs.",
	  "Capacitación de RC del Distrito 7 presencial en Sebampo en Etchojoa. 17:00 hrs.",
          "Capacitación para Estructura Jurídica-Zona Norte. 18:00 hrs.",
	  "Capacitación de RC del Distrito 7 presencial en Huatabampo. 18:30 hrs.",
          "Capacitación de RC del Distrito 1. 19:30 hrs."],
      6: ["Capacitación de RC del Distrito 4 presencial en Sahuaripa. 10:00 hrs.",
	  "Capacitación de RC del Distrito 3 presencial en domicilio particular en Hermosillo. 17:00 hrs.",
	  "Capacitación de RC del Distrito 3 presencial en Poblado Miguel Alemán. 17:00 hrs.",
	  "Capacitación de RC del Distrito 7 presencial en Buaysiacobe. 17:00 hrs.",
          "Capacitación para Estructura Jurídica-Zona Sur. 18:00 hrs."],
      7: ["Capacitación de RC del Distrito 4 presencial en Comité Municipal Morena en Nacozari. 9:00 hrs.",
          "Capacitación de RC del Distrito 7 presencial en domicilio particular en Navojoa. 9:00 hrs.",
          "Capacitación de RC del Distrito 1. 10:00 hrs.",
          "Capacitación de RC del Distrito 4 presencial en Aconchi. 11:00 hrs.",
          "Capacitación de RC del Distrito 4 presencial en Comité Municipal Morena en Cumpas. 12:30 hrs.",
          "Capacitación de RC del Distrito 2 presencial en Nuevo Nogales en Nogales. 14:00 hrs.",
          "Capacitación de RC del Distrito 7 presencial en Ejido Tapizuela en Alamos. 14:00 hrs.",
	  "Capacitación de RC del Distrito 3. 15:00 hrs.",
	  "Capacitación de RC del Distrito 7 presencial en Ejido El Maquipo en Alamos. 16:00 hrs.",
          "Capacitación de RC del Distrito 4 presencial en Asociación Ganadera en Moctezuma. 16:00 hrs.",
	  "Capacitación de RC del Distrito 7 presencial en La Bocana en Etchojoa. 17:00 hrs."],
      8: ["Capacitación de RC del Distrito 7 presencial en Ejido Basiroa en Alamos. 16:00 hrs.",
          "Capacitación de RC del Distrito 7 presencial en Sebampo en Etchojoa. 16:00 hrs.",
          "Capacitación de RC del Distrito 7 presencial en Ejido La Unión en Huatabampo. 17:00 hrs.",
          "Capacitación de RC del Distrito 1 presencial en Oficinas de Morena en Puerto Peñasco. 18:00 hrs."],
      9: ["Capacitación de RC del Distrito 7 presencial en El Rodeo en Etchojoa. 17:00 hrs."],
      10: ["Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Etchojoa. 17:00 hrs.",
           "Capacitación de RC del Distrito 1 presencial en Oficinas de Morena en Caborca. 17:00 hrs.",
           "Capacitación Municipal de RC. 18:00 hrs.",
           "Capacitación de RC del Distrito 1 presencial en Oficinas de Morena en Puerto Peñasco. 18:30 hrs."],
      11: ["Capacitación de RC del Distrito 7 presencial en Chucarit Etchojoa. 17:00 hrs.",
           "Capacitación de RC del Distrito 1. 18:00 hrs.",
           "Capacitación para Estructura Jurídica (Bacum, San Ignacio Río Muerto, Quiriego, Tesopaco y Cajeme). 18:00 hrs.",
           "Capacitación de RC del Distrito 5. 19:00 hrs."],
      12: ["Capacitación de RC del Distrito 7 presencial en Álamos. 16:00 hrs.",
           "Capacitación de RC del Distrito 6 presencial en Oficina ULS en Cajeme. 17:00 hrs.",
           "Capacitación para Estructura Jurídica (Navojoa, Etchojoa, Benito Juárez, Huatabampo y Álamos). 18:00 hrs.",
           "Capacitación de RC del Distrito 3. 18:00 hrs.",
           "Capacitación de RC del Distrito 1. 19:30 hrs."],
      13: ["Capacitación de RC del Distrito 2 presencial en Cananea. 10:30 hrs.",
           "Capacitación para Estructura Jurídica (Nacozari, Agua Prieta y Puerto Peñasco). 16:00 hrs.",
           "Capacitación de RC del Distrito 1 presencial en Oficinas de Morena en SLRC. 16:00 hrs.",
           "Capacitación de RG del Distrito 5. 16:00 hrs.",
           "Capacitación de RC del Distrito 7 presencial en Oficina de Morena en Navojoa. 16:00 hrs.",
           "Capacitación de RC del Distrito 1 presencial en Oficinas de Morena en Caborca. 16:00 hrs.",
           "Capacitación de RC del Distrito 3 presencial en Guerrero y Oaxaca en Hermosillo. 17:00 hrs.",
           "Capacitación de RC del Distrito 7 presencial en San Pedro Viejo en Etchojoa. 18:00 hrs.",
           "Capacitación de RC del Distrito 4 presencial en Empalme. 18:00 hrs."],
      14: ["Capacitación de RC del Distrito 7 presencial en El Saneal en Navojoa. 9:00 hrs.",
           "Capacitación de RC del Distrito 1 presencial en El Ocuca en Trincheras. 9:00 hrs.",
           "Capacitación de RC del Distrito 1 presencial en Oficina de Morena en Caborca. 10:00 hrs.",
           "Capacitación de RC del Distrito 7 presencial en La Bocana en Etchojoa. 10:00 hrs.",
           "Capacitación de RC del Distrito 2 presencial en Oficinas de Morena en Magdalena. 10:00 hrs.",
           "Capacitación de RC del Distrito 4 presencial en Local de Morena en Nacozari de García. 10:00 hrs.",
           "Capacitación de RC del Distrito 7 presencial en domicilio particular en Benito Juárez. 11:00 hrs.",
           "Capacitación de RC del Distrito 7 presencial en Masiaca Etchojoa. 12:00 hrs.",
           "Capacitación de RC del Distrito 4 presencial en Bácum. 14:00 hrs.",
           "Capacitación de RC del Distrito 7 presencial en Oficinas de Morena en Navojoa. 14:00 hrs.",
           "Capacitación de RC del Distrito 4 presencial en Local de Morena en Cumpas. 14:00 hrs.",
           "Capacitación de RC del Distrito 4 presencial en Ejido Antonio Rosales en Empalme. 14:30 hrs.",
           "Capacitación de RC del Distrito 2. 16:00 hrs.",
           "Capacitación de RC del Distrito 7 presencial en Bacobampo Etchojoa. 16:00 hrs.",
           "Capacitación de RC del Distrito 3 presencial en Poblado Miguel Alemán. 17:00 hrs."],
      15: ["Capacitación de RC del Distrito 7 presencial en El Potrero de Alcantar en Álamos. 16:00 hrs.",
           "Capacitación de Instructores de todos los distritos. 17:00 hrs."],
      17: ["Capacitación de RC del Distrito 7 presencial en Gerocoa en Álamos. 16:00 hrs.",
           "Capacitación de RC del Distrito 7 presencial en Ejido Palos Chinos en Álamos. 16:00 hrs."],
    }
  }
};
