cal_data = {
  2020: {
    10: { 1: ["Designación y/o ratificación de las y los Consejeros Electorales de los Consejos Distritales (inicio de periodo)."],
          30: ["Designación y/o ratificación de las y los Consejeros Electorales de los Consejos Distritales (fin de periodo)."], },
    11: { 1: ["Instalación de los Consejos Distritales (inicio de periodo)."],
          15: ["Instalación de los Consejos Distritales (fin de periodo).",
               "Inicio de precampaña de Gubernatura."] }
  },
  2021: {
    0: { 4: ["Inicio de precampaña de Diputaciones y ayuntamientos."],
         23: ["Fin de precampaña de Gubernatura.",
              "Fin de precampaña de Diputaciones y ayuntamientos."] },
    1: { 16: ["Inicio de registro de candidaturas para Gubernatura."],
         20: ["Fin de registro de candidaturas para Gubernatura."] },
    2: { 5: ["Campaña para la Gubernatura (inicio de periodo)."],
         15: ["Debates (inicio de periodo)."],
         16: ["Aprobación del número y ubicación de casillas extraordinarias y especiales."],
         25: ["Aprobación del número y ubicación de casillas básicas y contiguas."] },
    3: { 4: ["Inicio de registro de candidaturas para Diputaciones y Ayuntamientos."],
         8: ["Segunda insaculación y designación de funcionarios para mesas directivas de casilla.",
             "Fin de registro de candidaturas para Diputaciones y Ayuntamientos."],
         15: ["Primera publicación de la lista de ubicación de casillas en los lugares más concurridos del distrito electoral y en los medios electrónicos del Institudo."],
         16: ["Registro de representantes generales y ante mesas directivas de casilla (inicio de periodo).",
              "Sustitución de representantes generales y ante mesas directivas de casilla (inicio de periodo)."],
         24: ["Campaña para Diputaciones (inicio de periodo).",
              "Campaña para Ayuntamientos (inicio de periodo)."],
         26: ["Aprobación de los Mecanismos de recolección (inicio de periodo)."],
         27: ["Acreditación de representantes de partidos políticos y candidaturas independientes ante los mecanismos de recolección (inicio de periodo)."],
         28: ["Sustitución de representantes de partidos políticos y candidaturas independientes ante los mecanismos de recolección (inicio de periodo)."],
         30: ["Aprobación de los Mecanismos de recolección (fin de periodo)."]
    },
    4: { 6: ["Lista Nominal de Electores Definitiva con fotografía (inicio de periodo)."],
         14: ["Lista Nominal de Electores Definitiva con fotografía (fin de periodo)."],
         15: ["Segunda publicación de la lista de ubicación de casillas por causas supervivientes en los lugares más concurridos del distrito y en los medios electrónicos del Instituto (inicio de periodo)."],
         19: ["Lista Nominal de Electores con fotografía Producto de Instancias Administrativas y Resoluciones del Tribunal (ADENDA) (inicio de periodo)."],
         24: ["Lista Nominal de Electores con fotografía Producto de Instancias Administrativas y Resoluciones del Tribunal (ADENDA) (fin de periodo).",
              "Registro de representantes generales y ante mesas directivas de casilla (fin de periodo)."],
         25: ["Segunda publicación de la lista de ubicación de casillas por causas supervivientes en los lugares más concurridos del distrito y en los medios electrónicos del Instituto (fin de periodo)."],
         27: ["Sustitución de representantes generales y ante mesas directivas de casilla (fin de periodo)."] },
    5: { 2: ["Campaña para la Gubernatura (fin de periodo).",
             "Campaña para Diputaciones (fin de periodo).",
             "Campaña para Ayuntamientos (fin de periodo).",
             "Debates (fin de periodo)."],
         3: ["Acreditación de representantes de partidos políticos y candidaturas independientes ante los mecanismos de recolección (fin de periodo)."],
         4: ["Sustitución de representantes de partidos políticos y candidaturas independientes ante los mecanismos de recolección (fin de periodo)."],
         6: ["Jornada Electoral.",
             "PREP (inicio de periodo)."],
         7: ["Cómputos municipales (inicio de periodo).",
             "Cómputos distritales (inicio de periodo).",
             "PREP (fin de periodo)."],
         9: ["Cómputos municipales (fin de periodo)."],
         11: ["Cómputos distritales (fin de periodo)."],
         13: ["Cómputo estatal para la gubernatura."] }
  }
};
